# Generated by Django 5.2.4 on 2025-07-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_transaction_lineitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
