# Generated by Django 5.2.4 on 2025-07-18 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_transaction_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="user",
        ),
        migrations.DeleteModel(
            name="LineItem",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
