# Generated by Django 5.2.4 on 2025-07-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_transaction_lineitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
